version: '3.9'

services:
  booster:
    build: ./booster
    ports:
      - 3000:3000
    environment:
      BOOSTER_DB_USERNAME: booster
      BOOSTER_DB_PASSWORD: booster
      BOOSTER_DB_HOST: mysql-booster
      BOOSTER_DB_CONNECTION_TIMEOUT: 30s # MySQL takes its time to be available
    depends_on:
      - mysql-booster

  cargo:
    build: ./cargo
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongodb-cargo:27017/cargo"
    depends_on:
      - mongodb-cargo

  stage2:
    build: ./stage2
    profiles:
      - stage2
    environment:
      BOOSTER_URL: "http://booster:3000"
      TANKS: "Tank1,Tank2"
    depends_on:
      - booster

  mysql-booster:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booster
      MYSQL_USER: booster
      MYSQL_PASSWORD: booster

  mongodb-cargo:
    image: mongo:4.4
